"""Add global preferences

Revision ID: 872cbab6c68f
Revises: 5b6c3b9b2645
Create Date: 2025-11-30 21:33:57.940549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872cbab6c68f'
down_revision: Union[str, None] = '5b6c3b9b2645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('update_playlist_title', sa.Boolean(), nullable=True),
    sa.Column('update_playlist_uploader', sa.Boolean(), nullable=True),
    sa.Column('update_playlist_description', sa.Boolean(), nullable=True),
    sa.Column('update_playlist_thumbnail', sa.Boolean(), nullable=True),
    sa.Column('update_video_title', sa.Boolean(), nullable=True),
    sa.Column('update_video_uploader', sa.Boolean(), nullable=True),
    sa.Column('update_video_description', sa.Boolean(), nullable=True),
    sa.Column('update_video_thumbnail', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_preferences')
    # ### end Alembic commands ###
