"""Add playlist download path

Revision ID: c79174b52a90
Revises: 872cbab6c68f
Create Date: 2025-12-14 21:11:04.784382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c79174b52a90'
down_revision: Union[str, None] = '872cbab6c68f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_videos', sa.Column('custom_download_path', sa.String(), nullable=True))
    op.add_column('playlists', sa.Column('download_path', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'download_path')
    op.drop_column('playlist_videos', 'custom_download_path')
    # ### end Alembic commands ###
