"""Add playlist delete on cascade

Revision ID: f9dbc05d7582
Revises: d334636e9673
Create Date: 2025-04-02 16:06:55.720369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9dbc05d7582'
down_revision: Union[str, None] = 'd334636e9673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('playlist_videos_playlist_id_fkey', 'playlist_videos', type_='foreignkey')
    op.create_foreign_key(None, 'playlist_videos', 'playlists', ['playlist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playlist_videos', type_='foreignkey')
    op.create_foreign_key('playlist_videos_playlist_id_fkey', 'playlist_videos', 'playlists', ['playlist_id'], ['id'])
    # ### end Alembic commands ###
